server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb+srv://MDSohailAnsari:wQghcM2B1h1E2Vd4@cluster0.4e5fnrs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: studentManagementDB
  mail:
    host: smtp.gmail.com
    port: 587
    username: techtroopers9433@gmail.com
    password: oxuz wkes dzql hjng
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

JWT:
  SecretKey: mysecretkeymysecretkeymysecretkey123
